"""'Adding_users_roles'

Revision ID: c086e1e168be
Revises: a16b46cb4fcf
Create Date: 2023-07-02 19:37:06.597848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c086e1e168be'
down_revision = 'a16b46cb4fcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
