"""adding users and roles

Revision ID: ca9d77789056
Revises: c086e1e168be
Create Date: 2023-07-02 19:41:43.452802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9d77789056'
down_revision = 'c086e1e168be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
